project:
  type: website
  output-dir: docs

website:
  title: "Mark's Website"
  navbar:
    background: dark
    logo: images/paw.png
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: cats.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
